### ISSUE TITLE
Code review for Samuel

### ISSUE THREAD

**Issue by asiimwedismas** [SigmaSam/Main-Course-HTML--1--Embedding-Images-and-Video#1]
-Main element is supposed to be inside the body element not the other way

**Comment by emasdev** [comment]
- use something like https://raw.githack.com/ to test the page directly on the browser and point to it in the README.me file
- Try indent your code for making easy to read

**Comment by shubhsk88** [comment]
-Prefer to use a class often instead of giving id because Id can be only applied once in the markup
-For symbol, you can use use the fontawesome 
-Indent your HTML tag properly

**Comment by asiimwedismas** [comment]
Make it a habit to have one development branch on your machine, then create other feature branches and when u are done developing the feature, merge it into your local development branch and delete the now otherwise useless feature branch. 
Leaving around too many finished feature branches in git is the equivalent of not organizing your closet
